version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t blogs:latest .
      - docker tag blogs:latest 961515533175.dkr.ecr.us-east-1.amazonaws.com/blogs:latest
  post_build:
    commands:
      - docker push 961515533175.dkr.ecr.us-east-1.amazonaws.com/blogs:latest
      - printf '[{"name":"octblogs","imageUri":"%s"}]' 961515533175.dkr.ecr.us-east-1.amazonaws.com/blogs:latest > imagedefinitions2.json
artifacts:
  files: imagedefinitions2.json
